# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a set of commands using the runners shell

      - name: 'Get Date'
        run: echo "date=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build
        run: |
          chmod 755 ./.github/build.sh
          ./.github/build.sh
          echo "version=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d')" >> ./module.prop


      - name: Zip Folder
        run: |
          XZ_OPT=-9 tar cJf icons.tar.xz ./icons
          zip -r MIUI_Icons-${{steps.tag_version.outputs.new_tag}}.zip ./common
          zip -r MIUI_Icons-${{steps.tag_version.outputs.new_tag}}.zip ./META-INF
          zip -r MIUI_Icons-${{steps.tag_version.outputs.new_tag}}.zip ./icons.tar.xz
          zip -r MIUI_Icons-${{steps.tag_version.outputs.new_tag}}.zip ./module.prop

     ## 上传附件

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./MIUI_Icons-${{steps.tag_version.outputs.new_tag}}.zip

# This is a basic workflow to help you get started with Actions
